name: imaging
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipython
  - ipykernel
  - pip
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - seaborn
  - conda-forge::dask
  - conda-forge::dask-jobqueue
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::cudatoolkit
  - pip:
    - bm3d
    - napari[all]