name: imaging
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - scikit-image
  - conda-forge::dask
  - conda-forge::dask-jobqueue
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  - pip:
    - bm3d
    - cellpose
    - nd2