name: imaging
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipython
  - ipykernel
  - ipywidgets
  - pip
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - seaborn
  - numba
  - conda-forge::dask
  - conda-forge::dask-jobqueue
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::cudatoolkit
  - pip:
    - bm3d
    - napari[all]
    - cellpose[gui]
    - nd2