name: imaging
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - conda-forge::nodejs
  - conda-forge::jupyterlab
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.7
  - pytorch::torchvision
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - seaborn
  - numba
  - conda-forge::dask
  - conda-forge::dask-jobqueue
  - openpyxl
  - pip:
    - bm3d
    - napari[all]
    - cellpose[gui]
    - nd2